DEBUG = True
OFFLINE = False
MES_STS_CACHE_TIME = 30   # seconds
SPC_DATA_CACHE_TIME = 60  # SECONDS
SPEC_DATA_CACHE_TIME = 1800  # SECONDS
MES_QUERY_CACHE_SIZE = 10000

# -----------------MES TABLE SETTING -----------------------------------------------------
USE_GROUP_OPERATIONS = ['2900']
SEGMENT_ID_PERMIT_LENGTH = [8, 9]  # CAN LEN 8 OR 9
CHAR_DATA_VIRTUAL_LIMIT = 9999999999999999.