"""add puller info

Revision ID: 1cb9a1d9bc97
Revises: e5ab6ba583e2
Create Date: 2024-01-10 14:17:00.247996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cb9a1d9bc97'
down_revision: Union[str, None] = 'e5ab6ba583e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puller_info',
    sa.Column('puller_name', sa.VARCHAR(), nullable=False),
    sa.Column('puller_mes_id', sa.VARCHAR(), nullable=True),
    sa.Column('puller_mes_index', sa.Integer(), nullable=True),
    sa.Column('virtual_factory', sa.VARCHAR(), nullable=True),
    sa.Column('owner_name', sa.VARCHAR(), nullable=False),
    sa.Column('puller_type', sa.VARCHAR(), nullable=False),
    sa.Column('puller_description', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['owner_name'], ['test.user.user_name'], ),
    sa.PrimaryKeyConstraint('puller_name'),
    schema='test'
    )
    op.create_index(op.f('ix_test_puller_info_puller_mes_id'), 'puller_info', ['puller_mes_id'], unique=False, schema='test')
    op.create_index(op.f('ix_test_puller_info_puller_mes_index'), 'puller_info', ['puller_mes_index'], unique=False, schema='test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_puller_info_puller_mes_index'), table_name='puller_info', schema='test')
    op.drop_index(op.f('ix_test_puller_info_puller_mes_id'), table_name='puller_info', schema='test')
    op.drop_table('puller_info', schema='test')
    # ### end Alembic commands ###
