"""test_2

Revision ID: 3b772a9faaf4
Revises: 
Create Date: 2023-10-27 16:52:17.937232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b772a9faaf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_index(op.f('ix_test_user_email'), 'user', ['email'], unique=True, schema='test')
    op.create_table('accesstoken',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['test.user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('token'),
    schema='test'
    )
    op.create_index(op.f('ix_test_accesstoken_created_at'), 'accesstoken', ['created_at'], unique=False, schema='test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_accesstoken_created_at'), table_name='accesstoken', schema='test')
    op.drop_table('accesstoken', schema='test')
    op.drop_index(op.f('ix_test_user_email'), table_name='user', schema='test')
    op.drop_table('user', schema='test')
    # ### end Alembic commands ###
