"""add smaple plan model

Revision ID: 528b159b9cb3
Revises: 1cb9a1d9bc97
Create Date: 2024-01-23 15:02:53.787912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '528b159b9cb3'
down_revision: Union[str, None] = '1cb9a1d9bc97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_sample_lot_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_updated_time', sa.DateTime(), nullable=False),
    sa.Column('lot_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('oper', sa.VARCHAR(length=10), nullable=False),
    sa.Column('virtual_factory', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_index(op.f('ix_test_auto_sample_lot_stats_lot_id'), 'auto_sample_lot_stats', ['lot_id'], unique=True, schema='test')
    op.create_index(op.f('ix_test_auto_sample_lot_stats_oper'), 'auto_sample_lot_stats', ['oper'], unique=False, schema='test')
    op.create_table('sample_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_plan_name', sa.String(length=50), nullable=False),
    sa.Column('containment_rule_id', sa.Integer(), nullable=False),
    sa.Column('key_1', sa.VARCHAR(), nullable=False),
    sa.Column('key_2', sa.VARCHAR(), nullable=False),
    sa.Column('key_3', sa.VARCHAR(), nullable=False),
    sa.Column('sample_type', sa.Enum('SEGMENT_SEED_TAIL', 'FREQUENCY', 'INGOT_TAIL', 'INGOT_SEED', 'WAFER_DIRECT', name='tpsampletype'), nullable=False),
    sa.Column('frequency_type', sa.Enum('FIX_COUNT', 'FIX_INTERVAL_MM', 'EVERY_n_LOT', name='tpfrequencytype'), nullable=False),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('must_include_seed_tail', sa.Boolean(), nullable=False),
    sa.Column('plan_priority', sa.Integer(), nullable=False, comment='0 is the highest priority'),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('updated_user_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['containment_rule_id'], ['test.containment_rule.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['test.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_index(op.f('ix_test_sample_plan_key_1'), 'sample_plan', ['key_1'], unique=False, schema='test')
    op.create_index(op.f('ix_test_sample_plan_key_2'), 'sample_plan', ['key_2'], unique=False, schema='test')
    op.create_index(op.f('ix_test_sample_plan_key_3'), 'sample_plan', ['key_3'], unique=False, schema='test')
    op.create_index(op.f('ix_test_sample_plan_sample_plan_name'), 'sample_plan', ['sample_plan_name'], unique=True, schema='test')
    op.create_index(op.f('ix_test_sample_plan_updated_by'), 'sample_plan', ['updated_by'], unique=False, schema='test')
    op.create_table('auto_sample_tp_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_updated_time', sa.DateTime(), nullable=False),
    sa.Column('tp_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('oper', sa.VARCHAR(length=10), nullable=False),
    sa.Column('picked', sa.Boolean(), nullable=False),
    sa.Column('pick_time', sa.DateTime(), nullable=True),
    sa.Column('from_lot_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('from_sample_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_lot_id'], ['test.auto_sample_lot_stats.lot_id'], ),
    sa.ForeignKeyConstraint(['from_sample_plan_id'], ['test.sample_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_index(op.f('ix_test_auto_sample_tp_stats_from_lot_id'), 'auto_sample_tp_stats', ['from_lot_id'], unique=False, schema='test')
    op.create_index(op.f('ix_test_auto_sample_tp_stats_from_sample_plan_id'), 'auto_sample_tp_stats', ['from_sample_plan_id'], unique=False, schema='test')
    op.create_index(op.f('ix_test_auto_sample_tp_stats_oper'), 'auto_sample_tp_stats', ['oper'], unique=False, schema='test')
    op.create_index(op.f('ix_test_auto_sample_tp_stats_tp_id'), 'auto_sample_tp_stats', ['tp_id'], unique=False, schema='test')

    op.alter_column('containment_base_rule', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='test')
    op.alter_column('containment_rule', 'containment_object_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'wafer'::character varying"),
               schema='test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containment_rule', 'containment_object_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'wafer'::character varying"),
               schema='test')
    op.alter_column('containment_base_rule', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='test')

    op.drop_index(op.f('ix_test_auto_sample_tp_stats_tp_id'), table_name='auto_sample_tp_stats', schema='test')
    op.drop_index(op.f('ix_test_auto_sample_tp_stats_oper'), table_name='auto_sample_tp_stats', schema='test')
    op.drop_index(op.f('ix_test_auto_sample_tp_stats_from_sample_plan_id'), table_name='auto_sample_tp_stats', schema='test')
    op.drop_index(op.f('ix_test_auto_sample_tp_stats_from_lot_id'), table_name='auto_sample_tp_stats', schema='test')
    op.drop_table('auto_sample_tp_stats', schema='test')
    op.drop_index(op.f('ix_test_sample_plan_updated_by'), table_name='sample_plan', schema='test')
    op.drop_index(op.f('ix_test_sample_plan_sample_plan_name'), table_name='sample_plan', schema='test')
    op.drop_index(op.f('ix_test_sample_plan_key_3'), table_name='sample_plan', schema='test')
    op.drop_index(op.f('ix_test_sample_plan_key_2'), table_name='sample_plan', schema='test')
    op.drop_index(op.f('ix_test_sample_plan_key_1'), table_name='sample_plan', schema='test')
    op.drop_table('sample_plan', schema='test')
    op.drop_index(op.f('ix_test_auto_sample_lot_stats_oper'), table_name='auto_sample_lot_stats', schema='test')
    op.drop_index(op.f('ix_test_auto_sample_lot_stats_lot_id'), table_name='auto_sample_lot_stats', schema='test')
    op.drop_table('auto_sample_lot_stats', schema='test')
    # ### end Alembic commands ###
