"""add server stats table

Revision ID: 77a0484b84b9
Revises: 528b159b9cb3
Create Date: 2024-02-19 12:06:39.015639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77a0484b84b9'
down_revision: Union[str, None] = '528b159b9cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.VARCHAR(), nullable=False),
    sa.Column('client_ip', sa.VARCHAR(), nullable=False),
    sa.Column('server_ip', sa.VARCHAR(), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=False),
    sa.Column('duration', sa.Numeric(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=False),
    sa.Column('method', sa.VARCHAR(), nullable=False),
    sa.Column('scheme', sa.VARCHAR(), nullable=False),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_name', sa.VARCHAR(), nullable=True),
    sa.Column('error_flag', sa.Boolean(), nullable=True),
    sa.Column('traceback', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_index(op.f('ix_test_request_record_path'), 'request_record', ['path'], unique=False, schema='test')
    op.create_index(op.f('ix_test_request_record_request_time'), 'request_record', ['request_time'], unique=False, schema='test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_request_record_request_time'), table_name='request_record', schema='test')
    op.drop_index(op.f('ix_test_request_record_path'), table_name='request_record', schema='test')
    op.drop_table('request_record', schema='test')
    # ### end Alembic commands ###
