"""add ooc setting table

Revision ID: 834dd3f54209
Revises: a6345cba6d74
Create Date: 2024-03-04 16:41:07.973841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '834dd3f54209'
down_revision: Union[str, None] = 'a6345cba6d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ooc_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('containment_rule_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.VARCHAR(), nullable=False),
    sa.Column('lower_limit', sa.Float(), nullable=True),
    sa.Column('upper_limit', sa.Float(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('create_user_name', sa.VARCHAR(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('updated_user_name', sa.VARCHAR(), nullable=False),
    sa.Column('rule_delete_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['containment_rule_id'], ['test.containment_rule.id'], ),
    sa.ForeignKeyConstraint(['create_user_name'], ['test.user.user_name'], ),
    sa.ForeignKeyConstraint(['updated_user_name'], ['test.user.user_name'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_index(op.f('ix_test_ooc_rules_containment_rule_id'), 'ooc_rules', ['containment_rule_id'], unique=False, schema='test')
    op.create_index(op.f('ix_test_ooc_rules_spec_id'), 'ooc_rules', ['spec_id'], unique=False, schema='test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_record', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='test')

    op.drop_index(op.f('ix_test_ooc_rules_spec_id'), table_name='ooc_rules', schema='test')
    op.drop_index(op.f('ix_test_ooc_rules_containment_rule_id'), table_name='ooc_rules', schema='test')
    op.drop_table('ooc_rules', schema='test')
    # ### end Alembic commands ###
