DEBUG = True
MES_STS_CACHE_TIME = 100   # seconds
SPC_DATA_CACHE_TIME = 100  # SECONDS


# -----------------MES TABLE SETTING -----------------------------------------------------
USE_GROUP_OPERATIONS = ['2900']
SEGMENT_ID_PERMIT_LENGTH = [8, 9]  # CAN LEN 8 OR 9
CHAR_DATA_VIRTUAL_LIMIT = 9999999999999999.